language: node_js
node_js:
- '6'
- '7'
before_deploy: yarn run production
deploy:
  provider: heroku
  api_key:
    secure: HgcCkFe4h+dzxUU0ENjkDZEYDd8poyfmsIBI6JnfOwzwtiUzjXU/DMJYklYv+q+bpjLb3rAl257Fd76bKE/gjKnpzOXyiRnE215AHx2vqhTzyg2dd6Xrh9toiHCrOTmqHBqd9ilNNBiQ5VL0HY2M7fmRVOEcuXnchf9S0VxlwYhFzaADGLNIh0MwXGzdsIaKAOl4ZFe6yBZE5Ye2CwDWYv0KJdGfEV33ICnc245FJqa6TESAgzmFS+AHPzwbLNoPTUmIuJTJvC/8Cej7x1lf9UDZ8u8suhh+4lfj8PVELQIVsRidpmSrReZbGKnQZR+aOY7FsfcDXjk7RkrSFekOlm8TkYXRHYPEERWxGUkdfMjRwMk8riV89ItQt0MtV7iQsnnuh8a/ELn+jIIJhLghIKv1oMx9XVfUXidGGpQgpO6JxFAoKNh794YTQIOwyk9G0SoNZ+T4/8iTeN01q63SfxFJR2CNbtC01eDmrtESMffsvXNeDTcy6McNa3naNcLmZTyFL7zj61T7jdrDjQqvjpaxmM81UicPvCJgUmMsvwnXp0HXJN48jw4FDJYxqkpv1IlCMDZqy5ChVJmuqctJZk3nCNLbXx9YdOH5XBbPaVIdxnSV1jv4nIbdL3VQpreekHx4S1V3RhTh+svMaZoZmTZGC1j6Vatha/hBpu7HEKs=
  app: keepo-client
  on:
    repo: KeepoApp/keepo-client
  skip_cleanup: true
branches:
  only:
  - master
